### ISSUE TITLE
Not holding any coins?

### ISSUE THREAD

**Issue by dascar5** [CyberPunkMetalHead/Binance-volatility-trading-bot#197]
The bot has been running for an hour now connected to a live account using real money, but it hasn't bought anything yet? No errors in terminal. Just wondering if its supposed to be like that or?

**Comment by celltronic01** [comment]
hi
check your config.yml file and see what % is set for coin movement. Due to market conditions, you will have to adjust it. For example, I have set my movement % to 0.75. So if the coin moves up .75%, It will buy it and take profit at 4%. As market conditions improve within next week or 2, we can re adjust those numbers to for example coin movement 1.24% and Take profit to 6% or maybe even to 8% and so on and so forth.  But whatever you do, please do it to your desired wanting.
