### ISSUE TITLE
Suggestion - show wait time

### ISSUE THREAD

**Issue by campbellkerr** [CyberPunkMetalHead/Binance-volatility-trading-bot#6]
Found this handy for debug/sanity

`print(f'not enough time has passed yet... Waiting {TIME_DIFFERENCE} minute(s)')`

![image](https://user-images.githubusercontent.com/38451588/117572006-5052d480-b114-11eb-88f2-b4e1fbcf419d.png)

**Comment by Amraki** [comment]
It may just be very late but I'm thinking there may be an underlying issue here.

TIME_DIFFERENCE is a user defined constant.
It would be nice if the message showed the remaining time until TIME_DIFFERENCE.

This brings me to `time.sleep(60*TIME_DIFFERENCE)` just below that.
Like above, should this always wait the same amount of time or would it be more beneficial to have it be a calculation of specified TIME_DIFFERENCE minus elapsed time or something similar?

-- New to Python. Please be nice 😁

**Comment by getsec** [comment]
implemented.
